source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'QNLiveKit' do
  
  use_frameworks!
  
  pod 'QNRTCKit-iOS','4.0.0'
  pod 'PLPlayerKit', '3.4.7'
  pod 'Masonry', '1.1.0'
  pod 'SDWebImage',' 5.12.2'
  pod 'MJExtension','3.4.1'
  pod 'YYCategories','1.0.4'
  pod 'AFNetworking','4.0.1'

  target 'QNLiveKitTests' do
    inherit! :search_paths
    # Pods for testing
  end


end